import { useState } from "react";
import Head from "next/head";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import { FaFacebook, FaInstagram, FaLinkedinIn } from "react-icons/fa";
import Image from "next/image";
import myPic from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>ALI Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-gray-200">
        <section className="min-h-screen ">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">ALI</h1>
            <ul className="flex items-center">
              {darkMode ? (
                <li
                  onClick={() => {
                    setDarkMode(false);
                  }}
                >
                  <BsFillMoonStarsFill className="text-2xl cursor-pointer text-gray-200" />
                </li>
              ) : (
                <li
                  onClick={() => {
                    setDarkMode(true);
                  }}
                >
                  <BsFillSunFill className="text-2xl cursor-pointer" />
                </li>
              )}

              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white py-2 px-4 rounded ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-5">
            <h2 className="text-4xl py-2 text-teal-600 font-medium md:text-6xl">
              ALI Ghaniem
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">
              Cyber Security Specialist
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-300">
              An ambitious and driven individual. Thrive in a goal-oriented
              environment where I can constantly challenge myself personally and
              professionally.
            </p>
          </div>
          {/* <div className="text-5xl flex justify-center gap-16 text-gray-600 py-2">
            <FaFacebook className="hover:text-teal-400 transition-all cursor-pointer" />
            <FaInstagram className="hover:text-teal-400 transition-all cursor-pointer" />
            <FaLinkedinIn className="hover:text-teal-400 transition-all cursor-pointer" />
          </div> */}
          <div className="relative mx-auto overflow-hidden bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mx-auto mt-20 md:h-96 md:w-96">
            <Image
              alt="my picture"
              layout="fill"
              objectFit="cover"
              src={myPic}
            />
          </div>
        </section>
        {/* second page */}
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I am always looking for an{" "}
              <span className="text-teal-500"> opportunity </span>to do better
              and grow. These characteristics have helped me achieve
              <span className="text-teal-500"> success</span>
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I offer from a wide range of services, including programing and
              web development services also teaching
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <div className="flex justify-center">
                <Image src={design} alt="" width="100" height="1000" />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa
                consectetur nam architecto magnam.
              </p>
              <h4 className="py-4 text-teal-600">I will use this tools</h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Illustrator
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <div className="flex justify-center">
                <Image src={consulting} alt="" width="100" height="1000" />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">Pen Testing</h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa
                consectetur nam architecto magnam.
              </p>
              <h4 className="py-4 text-teal-600">I will use this tools</h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Kali Linux
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Metasploit
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-300">
                Burp Suite
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <div className="flex justify-center">
                <Image src={code} alt="" width="100" height="1000" />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Hashing and Encryption
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa
                consectetur nam architecto magnam.
              </p>
              <h4 className="py-4 text-teal-600">I will use this tools</h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">AES</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">DES</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">RSA</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I am always looking for an{" "}
              <span className="text-teal-500"> opportunity </span>to do better
              and grow. These characteristics have helped me achieve
              <span className="text-teal-500"> success</span>
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I offer from a wide range of services, including programing and
              web development services also teaching
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-wrap lg:flex-row">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                alt="website 1"
                src={web1}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                alt="website 2"
                src={web2}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                alt="website 3"
                src={web3}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                alt="website 4"
                src={web4}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                alt="website 5"
                src={web5}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                alt="website 6"
                src={web6}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
